name: Docker Image CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo Code

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REPO_1 }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REPO_2 }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: |
        docker build -t ${{ secrets.REPO_1 }}/${{ secrets.IMAGE_NAME }}:latest .
        docker push ${{ secrets.REPO_1 }}/${{ secrets.IMAGE_NAME }}:latest
        docker tag ${{ secrets.REPO_1 }}/${{ secrets.IMAGE_NAME }} ${{ secrets.REPO_2 }}/${{ secrets.IMAGE_NAME }}
        docker push ${{ secrets.REPO_2 }}/${{ secrets.IMAGE_NAME }}
      
    - uses: 8398a7/action-slack@v3
      name: Slack Notification
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.
